baseURL = "https://nycehs.github.io/ehs-data-portal-frontend-temp/"
canonifyURLs = "true"
relativeURLs = "true"
languageCode = "en-us"
title = "Environment & Health Data Portal"
enableRobotsTXT = true
metaDataFormat = "yaml"
theme = "dohmh"
publishDir = "docs"
[taxonomies]
  tag = "tags"
  category = "categories"
  keyword = "keywords"

[menu]

  [[menu.main]]
    identifier = "01"
    name = "Home"
    pre = "<span class='text-primary'><i class='fa fa-home' aria-hidden='true'></i></span>"
    url = "/"
    weight = -110

  [[menu.main]]
    identifier = "02"
    name = "Data Stories"
    pre = "<span class='text-primary'><i class='fas fa-passport' aria-hidden='true'></i></span>"
    url = "/data_stories/"
    weight = -100
  
  [[menu.main]]
    identifier = "03"
    name = "Data Explorer"
    pre = "<span class='text-primary'><i class='fas fa-chart-line' aria-hidden='true'></i></span>"
    url = "/data_explorer/"
    weight = -70
  
  [[menu.main]]
    identifier = "04"
    name = "Neighborhood Reports"
    pre = "<span class='text-primary'><i class='fas fa-map-marked-alt' aria-hidden='true'></i></span>"
    url = "/neighborhood_reports/"
    weight = -90

  [[menu.main]]
    identifier = "05"
    name = "Key Topics"
    pre = "<span class='text-primary'><i class='fas fa-star' aria-hidden='true'></i></span>"
    url = "/key_topics/"
    weight = -80