baseURL = "https://a816-dohbesp.nyc.gov/IndicatorPublic/"
canonifyURLs = false
relativeURLs = false
languageCode = "en-us"
title = "Environment & Health Data Portal"
enableRobotsTXT = true
metaDataFormat = "yaml"
theme = "dohmh"
publishDir = "docs"
paginate = 9
ignoreFiles = ['Simplified.Chinese', 'Spanish']
timeZone = "America/New_York"
# enableGitInfo = true

[params]
  data_repo = "https://raw.githubusercontent.com/nychealth/EHDP-data/"

[caches]
    [caches.getresource]
      dir = ':cacheDir/:project'
      maxAge = -1

[imaging]
  anchor = 'Smart'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 95
  resampleFilter = 'MitchellNetravali'

[markup.goldmark.parser]
  autoHeadingID = false # remove md headings from pagefind results

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[markup.goldmark.parser.attribute]
  block = false
  title = true # allow apending attributes to md headings

[languages.en]
  languageName = "English"
  weight = 1
  [languages.en.params]
    languageDesc = "English"

[languages.es]
  languageName = "Español"
  weight = 2
  [languages.es.params]
    languageDesc = "Spanish-US"

[languages.zh]
  languageName = "中文"
  weight = 3
  [languages.zh.params]
    languageDesc = "Chinese-Simplified"


[taxonomies]
  tag = "tags"
  category = "categories"
  keyword = "keywords"


[menu]

  [[menu.main]]
    identifier = "02"
    name = "Data Stories"
    pre = "<span class='text-primary data-stories'><i class='fas fa-passport' aria-hidden='true'></i></span>"
    url = "/data-stories/"
    weight = -100

  [[menu.main]]
    identifier = "03"
    name = "Data Explorer"
    pre = "<span class='text-primary data-explorer'><i class='fas fa-chart-line' aria-hidden='true'></i></span>"
    url = "/data-explorer/"
    weight = -70

  [[menu.main]]
    identifier = "04"
    name = "Neighborhood Reports"
    pre = "<span class='text-primary n-reports'><i class='fas fa-map-marked-alt' aria-hidden='true'></i></span>"
    url = "/neighborhood-reports/"
    weight = -90

  [[menu.main]]
    identifier = "05"
    name = "Key Topics"
    pre = "<span class='text-primary kt-accent'><i class='fas fa-star' aria-hidden='true'></i></span>"
    url = "/key-topics/"
    weight = -110

  [[menu.main]]
    identifier = "06"
    name = "Search"
    # pre = "<span class='sr-only'>Search</span><span class='fas fa-search fa-lg'></span>"
    # url = ""
    weight = -50

  [[menu.main]]
    identifier = "07"
    name = "Data Features"
    pre = "<span class='df-accent'><i class='fas fa-chart-bar' aria-hidden='true'></i></span>"
    url = "/data-features/"
    weight = -95


[module]

  [[module.mounts]]
    source = "node_modules"
    target = "assets/node_modules"

 [[module.mounts]]
    source = "content"
    target = "content"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "layouts"
    target = "layouts"

  [[module.mounts]]
    source = "data"
    target = "data"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "i18n"
    target = "i18n"

  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"