baseURL = "https://nychealth.github.io/EH-dataportal/"
canonifyURLs = true
relativeURLs = false
languageCode = "en-us"
title = "Environment & Health Data Portal"
enableRobotsTXT = true
metaDataFormat = "yaml"
theme = "dohmh"
publishDir = "docs"
paginate = 9
ignoreFiles = ['Simplified.Chinese', 'Spanish']

[params]
  data_repo = "https://raw.githubusercontent.com/nychealth/EHDP-data/"
  sitepath = "/EH-dataportal"

[imaging]
  anchor = 'Smart'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 95
  resampleFilter = 'MitchellNetravali'

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[languages.en]
  languageName = "English"
  languageDesc = "English"
  weight = 1

[languages.es]
  languageName = "Español"
  languageDesc = "Spanish-US"
  weight = 2

[languages.cn]
  languageName = "中文"
  languageDesc = "Chinese-Simplified"
  weight = 3


[taxonomies]
  tag = "tags"
  category = "categories"
  keyword = "keywords"


[menu]

  [[menu.main]]
    identifier = "01"
    name = "Home"
    pre = "<span class='text-primary'><i class='fa fa-home' aria-hidden='true'></i></span>"
    url = "/"
    weight = -110

  [[menu.main]]
    identifier = "02"
    name = "Data Stories"
    pre = "<span class='text-primary'><i class='fas fa-passport' aria-hidden='true'></i></span>"
    url = "/data-stories/"
    weight = -100
  
  [[menu.main]]
    identifier = "03"
    name = "Data Explorer"
    pre = "<span class='text-primary'><i class='fas fa-chart-line' aria-hidden='true'></i></span>"
    url = "/data-explorer/"
    weight = -70
  
  [[menu.main]]
    identifier = "04"
    name = "Neighborhood Reports"
    pre = "<span class='text-primary'><i class='fas fa-map-marked-alt' aria-hidden='true'></i></span>"
    url = "/neighborhood-reports/"
    weight = -90

  [[menu.main]]
    identifier = "05"
    name = "Key Topics"
    pre = "<span class='text-primary'><i class='fas fa-star' aria-hidden='true'></i></span>"
    url = "/key-topics/"
    weight = -80

  [[menu.main]]
    identifier = "06"
    name = "Search"
    # pre = "<span class='sr-only'>Search</span><span class='fas fa-search fa-lg'></span>"
    # url = ""
    weight = -50


[module]

  [[module.mounts]]
    source = "node_modules/arquero/dist/arquero.min.js"
    target = "assets/node_modules/arquero/dist/arquero.min.js"

  [[module.mounts]]
    source = "node_modules/datatables.net/js/jquery.dataTables.min.js"
    target = "assets/node_modules/datatables.net/js/jquery.dataTables.min.js"

  [[module.mounts]]
    source = "node_modules/datatables.net-dt/css/jquery.dataTables.min.css"
    target = "assets/node_modules/datatables.net-dt/css/jquery.dataTables.min.css"

  [[module.mounts]]
    source = "node_modules/datatables.net-buttons/js/dataTables.buttons.min.js"
    target = "assets/node_modules/datatables.net-buttons/js/dataTables.buttons.min.js"

  [[module.mounts]]
    source = "node_modules/datatables.net-buttons-dt/css/buttons.dataTables.min.css"
    target = "assets/node_modules/datatables.net-buttons-dt/css/buttons.dataTables.min.css"

  [[module.mounts]]
    source = "node_modules/datatables.net-buttons/js/buttons.html5.min.js"
    target = "assets/node_modules/datatables.net-buttons/js/buttons.html5.min.js"

  [[module.mounts]]
    source = "node_modules/datatables.net-buttons/js/buttons.print.min.js"
    target = "assets/node_modules/datatables.net-buttons/js/buttons.print.min.js"

  [[module.mounts]]
    source = "node_modules/datatables.net-rowgroup/js/dataTables.rowGroup.min.js"
    target = "assets/node_modules/datatables.net-rowgroup/js/dataTables.rowGroup.min.js"
  
  [[module.mounts]]
    source = "node_modules/jszip/dist/jszip.min.js"
    target = "assets/node_modules/jszip/dist/jszip.min.js"
  
  [[module.mounts]]
    source = "node_modules/pdfmake/build/pdfmake.min.js"
    target = "assets/node_modules/pdfmake/build/pdfmake.min.js"
  
  [[module.mounts]]
    source = "node_modules/pdfmake/build/vfs_fonts.js"
    target = "assets/node_modules/pdfmake/build/vfs_fonts.js"

  [[module.mounts]]
    source = "node_modules/vega/build/vega.min.js"
    target = "assets/node_modules/vega/build/vega.min.js"

  [[module.mounts]]
    source = "node_modules/vega-lite/build/vega-lite.min.js"
    target = "assets/node_modules/vega-lite/build/vega-lite.min.js"

  [[module.mounts]]
    source = "node_modules/vega-embed/build/vega-embed.min.js"
    target = "assets/node_modules/vega-embed/build/vega-embed.min.js"

  [[module.mounts]]
    source = "node_modules/d3/dist/d3.min.js"
    target = "assets/node_modules/d3/dist/d3.min.js"

 [[module.mounts]]
    source = "content"
    target = "content"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "layouts"
    target = "layouts"

  [[module.mounts]]
    source = "data"
    target = "data"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "i18n"
    target = "i18n"

  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"