baseURL = "https://nychealth.github.io/EH-dataportal/"
[params]
    data_branch = "production"

[caches]
    [caches.getresource]
      dir = ':cacheDir/:project'
      maxAge = 0

[caches]
    [caches.getresource]
      dir = ':cacheDir/:project'
      maxAge = 0