name: Hugo Build to `dev-test` branch

# run action on a merged PR on "development"

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
    types:
      - closed

jobs:
  deploy:
    name: Build & Deploy w/ Hugo
    runs-on: ubuntu-20.04

    # only run the action if it's a push or the PR was merged

    if: github.event_name == 'push' || github.event.pull_request.merged == true

    # don't run two of these jobs at the same time

    concurrency: # don't run two of these jobs at the same time
      group: ${{ github.workflow }}-${{ github.ref_name }} # ref name is branch name, so only one job on a branch will run at a time
      cancel-in-progress: true # this makes it so that only the most recent job is run

    # define job's steps

    steps:

      # setting line endings to LF to match line endings in source files (which were used to compute resource integrity)

      - name: set git EOL
        run: |
          git config --global core.eol lf
          git config --global core.autocrlf input

      # using checkout action

      - name: Checkout
        uses: actions/checkout@v3

      # set up node and cache for npm

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "npm"

      - name: Installing npm
        run: npm install

      # set up cache for node modules

      - name: Cache node_modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # update npm dependencies (if cached)

      - name: Update dependencies
        if: steps.cache-nodemodules.outputs.cache-hit == 'true'
        run: npm update

      # install npm dependencies (if not cached)

      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm install grunt
          npm install lunr
          npm install yamljs
          npm install string
          npm install url

      # set up Hugo

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.105.0"
          extended: true

      # cache Hugo modules

      - name: Hugo cache
        uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      # build site with Hugo

      - name: Hugo Build
        run: hugo --environment dev_test --cleanDestinationDir

      # run gruntfile action

      - name: Build index with Grunt
        run: |
          cd '${{ github.workspace }}'
          grunt lunr-index

      # commit built index

      - name: Commit changes to PagesIndex.json
        uses: elstudio/actions-js-build/commit@v4
        with:
          commitMessage: Regenerate index

      # publish to "deploy" branch

      - name: Publish to "dev-test"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: dev-test
          publish_dir: ./docs/
          enable_jekyll: false
